### ISSUE TITLE
Develop UIs for Login and Account Creation

### ISSUE THREAD

**Issue by MerpKun** [takhimhack/cse442#16]
**Task Tests**

*Test 1*
1) Create login/registration page based on figma prototype https://www.figma.com/proto/gCkiojvUUTVRxdyR1lCVWk/UB-Office-Hour-App?node-id=0%3A1&scaling=min-zoom&page-id=0%3A1

*Test 2*
1) Accept if all the following hold for the deployed app, https://cse442-office-hours-app.herokuapp.com/:
1.1) When one clicks on Log In button from index.html it redirects to home.html
1.2) When one clicks on "Create an account" it redirects to register.html
1.3) When one clicks on "Register" it redirects to home.html

**Comment by takhimhack** [comment]
Test 1
1) Create login/registration page based on figma prototype 
2) When one clicks on Log In button from index.html it redirects to home.html
3) When one clicks on "Create an account" it redirects to register.html
4) When one clicks on "Register" it redirects to home.html
